### ISSUE TITLE
Optionally save ids of geometry errors

### ISSUE THREAD

**Issue by aaronlidman** [mapbox/minjur#1]
During processing Minjur comes across items with geometry issues and doesn't process them.

From the latest planet:

> Number of geometry errors (not written to output): 7935

@joto is there anyway we could keep the node/way id of these geometry issues so we can look into fixing them? Maybe as an optional argument much like `-d` for dump, maybe `-e` for errors?

Also what are these geometry errors, what are you looking at specifically? If there are multiple types, could we also log the type of error it is?

**Comment by joto** [comment]
There are just a few reasons when this can happen. It is unlikely, but the OSM database could be corrupted in some way. I just found two such problems last week which must be corrected there (probably have by now).

The other reason is a way which result somehow in an invalid linestring. There are a few cases how this can happen:
- Ways which contain only one node. Happens. Can be found and fixed here: 
  http://tools.geofabrik.de/osmi/?view=geometry&lon=-12.00000&lat=25.00000&zoom=3&overlays=single_node_in_way
- Duplicate node in way, ie the same node several times in a row. If this leads to less than 2 "real nodes", we get a geometry error. Can be found and fixed here:
  http://tools.geofabrik.de/osmi/?view=geometry&lon=-12.00000&lat=25.00000&zoom=3&overlays=duplicate_node_in_way
- All of the above when there are enough nodes, but they have the same location, so in the end there is, again, less than two locations in the way. Probably very rare. But we should also check for several nodes in the same location in some QA tool.

We can certainly add some error output here, would not be a big deal. But maybe that should be part of some bigger QA effort?
