### ISSUE TITLE
Add travis support.

### ISSUE THREAD

**Issue by joto** [mapbox/minjur#10]
@springmeyer can you enable travis support for this repository? I have alrady added the necessary scripts.

**Comment by springmeyer** [comment]
@joto I am unable to add support since for some reason i'm not an admin on this repo. /cc @aaronlidman who may be able to do it.

**Comment by springmeyer** [comment]
Okay, I got admin access now and have enabled travis: https://travis-ci.org/mapbox/minjur/builds/97281708
