### ISSUE TITLE
Drop points with only source and/or created_by tags?

### ISSUE THREAD

**Issue by rclark** [mapbox/minjur#12]
There are a lot of these points, but I don't believe that they really represent anything thematically interesting. Would it be acceptable to drop these from the output geojson?

example: http://www.openstreetmap.org/node/23137494

Are there other tags that nodes might have that should not whitelist them for inclusion in the output geojson?

**Comment by joto** [comment]
These are QA tiles, so maybe we _want_ to keep strange tag combinations, so we can write checks for them or so. It is certainly doable to filter more, though.

**Comment by rclark** [comment]
cc @geohacker @mikelmaron curious what you think about these kinds of nodes from the QA perspective.

**Comment by mikelmaron** [comment]
What volume are we talking about here? And in what system --- dynamosm? OSMQATiles?

A node with only these tags --- well that node shouldn't have any tags on it actually. The only QA check we'd want to do is find them, and remove the unnecessary tags. Cleaning these up isn't a high priority, so not a big deal if they're not represented.

**Comment by geohacker** [comment]
@rclark I'd keep them in QA tiles, if it's not making us hit a performance wall. There's soon going to be a tag validator which will help us flag and clean these on a regular basis.

**Comment by rclark** [comment]
Sounds good let's keep 'em.
