### ISSUE TITLE
Unify minjur and minjur-mp

### ISSUE THREAD

**Issue by rclark** [mapbox/minjur#13]
There's some confusion between the CLI tools that this library builds. Just opening a ticket to track this. The big differences are that `minjur` doesn't make multipolygons, and from https://github.com/mapbox/minjur/issues/8#issuecomment-184732800

> minjur can work with updates and minjur-mp doesn't

I think we're in the early stages here and this doesn't have to happen right away, but in the long run it'll be more clear if we can unify these two.

**Comment by joto** [comment]
`minjur` was always a hack with limited usability because of the missing multipolyon support. The question is: Is anybody still using it, now that `minjur-mp` exists. If not, we can just scrap it, and rename `minjur-mp` to `minjur`. Any opinions?

/cc @rclark, @aaronlidman, @springmeyer

**Comment by rclark** [comment]
:+1: from me -- I'm not an active `minjur-without-mp` user.

**Comment by springmeyer** [comment]
👍

**Comment by aaronlidman** [comment]
Also 👍 but I'm seeing a few internal users still on plain old minjur and not checking out a specific version. If we switch this on them things will break.

Let me ticket this internally so we can get people to either switch or checkout to a particular commit.

**Comment by aaronlidman** [comment]
Ok nevermind, everyone looks good. 👍 👍 👍

**Comment by DenisCarriere** [comment]
👍 minjur should support relation by default, good call.

**Comment by joto** [comment]
Minjur will be phased out in favour of the new `osmium export` command (#28). So this will not be changed in minjur any more.
