### ISSUE TITLE
Added -i option for top-level id

### ISSUE THREAD

**Issue by joto** [mapbox/minjur#15]
@rclark I have cleaned up the code somewhat, fixed the prefix-thing and added an option `-i` to add a unique top-level id to all features. The format of that id is hard-coded. Not sure this is exactly what is needed, but wanted to get things started.

**Comment by rclark** [comment]
The format of this id is just fine with me since we also have clear pointers to openstreetmap objects in the geojson's properties.

My only question would be, should this be a flag? Or just standard behavior? Is there a case where having ids would be problematic?

**Comment by joto** [comment]
It makes the output bigger, so I thought I make it optional. But I don't feel strongly about that.
