### ISSUE TITLE
Ubuntu compile error: cout is not a member of std

### ISSUE THREAD

**Issue by jenningsanderson** [mapbox/minjur#20]
C++ is definitely not my forte, so not sure if this was unique to my environment, but I was having compile issues with `minjur-generate-tilelist.cpp`

This was solved by adding: 

```
#include <iostream>
```

at the top of `minjur-generate-tilelist.cpp`

**Comment by joto** [comment]
Thanks, I have fixed this (and many other include problems) in 363cc85.
