### ISSUE TITLE
Duplicate features with minjur-mp

### ISSUE THREAD

**Issue by jasonbeverage** [mapbox/minjur#21]
I've been using minjur along with tippecanoe to generate vector tiles from the osm. This is working well except for the fact that multipolygons aren't supported in regular minjur so we have some missing data.  I switched to minjur-mp, and it produces the multipolygon data but it also appears that I get duplicate data for some features, one as a Line feature type and another as a Polygon feature.

For example, I'll get a line string building, and then also a polygon building, which is not what I want.  I'd like to just get a single polygon feature.

It looks like regular minjur has support for determining whether a given way should be emitted as a line string OR a polygon here:
https://github.com/mapbox/minjur/blob/master/minjur.cpp#L57

minjur-mp seems to emitting the same feature as BOTH a line string and a polygon.  Am I missing something or is this just the result of the filter in minjur not being ported to minjur-mp?

**Comment by joto** [comment]
Generally it is impossible to decide in OSM whether a feature is a "line feature" or a "polygon feature". There are some heuristics, but they are not perfect. I think minjur shouldn't force you into one interpretation of the OSM data or the other. This gives you the option of, for instance, simply ignoring any line feature tagged as building, but doesn't prevent you from seeing that data if it is necessary for your use case.

And yes, some heuristic (a simple list) is implemented in minjur, but not minjur-mp.

**Comment by joto** [comment]
The upcoming `osmium export` command (#28) supports setting a list of "polygon tags" and "linestring tags" in the config file. See its manual page for details.

Please have a look whether this does all it needs to do.

Because minjur is being phased out, this will not be changed in minjur any more.

**Comment by springmeyer** [comment]
Thanks for the details @joto. Anyone interested in testing osmium-tool please see https://github.com/mapbox/minjur/issues/28#issuecomment-298798206.
