### ISSUE TITLE
minjur-mp support memberlist 

### ISSUE THREAD

**Issue by suze521** [mapbox/minjur#22]
Is minjur support memberlist?  I found the result only have tag. is there some option to support memberlist such as subare?

**Comment by suze521** [comment]
and i want  feature_collection geojson, not vector<feature>, because i use https://github.com/mapbox/geojson-cpp to generate geojson to mapbox geometry

**Comment by joto** [comment]
@suze521 I am not sure what you mean by "memberlist"? Can you elaborate on what you need and why?
