### ISSUE TITLE
Minjur crashes on input files with invalid geometry/location instead of skipping them and writing to error file

### ISSUE THREAD

**Issue by buma** [mapbox/minjur#25]
I'm trying to create history of my country mapping. I downloaded planet history, extracted my country and used minjur for each wanted date and it worked. Then I updated extract with change files and minjur started failing because of invalid geometry in ways and nodes created before update times.

Minjur crashes because of assert fails because of invalid location in Tile function:
>minjur: /usr/include/osmium/geom/tile.hpp:97: osmium::geom::Tile::Tile(uint32_t, const osmium::Location&): Assertion `location.valid()' failed.
>Aborted (core dumped)

I have to figure out why the location is invalid (both coordinates are undefined for some reason) but the problem is that IMHO `invalid_location` exception should be thrown node/way should be skipped and written to error_file, in line [182](https://github.com/mapbox/minjur/blob/master/minjur.cpp#L182) but instead location.valid() is checked inside assert in libosmium and this fails and everything stops.

I'm using commit  b4508a0f1daf69d60778958fe2e6b272a1582e56 of minjur and libosmium 2.10.3.

**Comment by buma** [comment]
I checked and libosmium is installed with -DCMAKE_BUILD_TYPE=Release and minjur also with Release build type according to CmakeCache.txt in minjur build folder.

**Comment by joto** [comment]
The upcoming `osmium export` command (#28) supports more flexible error handling. It should behave as you said it should behave. See its manual page for details.

Please have a look whether this does all it needs to do.

Because minjur is being phased out, this will not be changed in minjur any more.

**Comment by buma** [comment]
I'll check osmium export tool. Thanks.

**Comment by springmeyer** [comment]
Closing, please help test osmium-tool per https://github.com/mapbox/minjur/issues/28#issuecomment-298798206
