### ISSUE TITLE
How slow does minjur-mp？

### ISSUE THREAD

**Issue by lygstate** [mapbox/minjur#31]
How much time I need when converting planet.osm.pbf?
My computer are 8core 16 thread(ryzen 1700x) + 16GB memory.

**Comment by joto** [comment]
You'll need at least 64 GB to make this reasonably fast (< 1h). With only 16GB you'll probably need to use `-l dense_file_array` to store the index file on disk which will slow things down considerably. Never tried it with a full planet, so no idea how long this will take.

**Comment by lygstate** [comment]
@joto 
```
  -e, --error-file=FILE      Write errors to file
  -h, --help                 This help message
  -v, --version              Display version
  -i, --with-id              Add unique id to each feature
  -l, --location-store=TYPE  Set location store
  -L, --list-location-stores Show available location stores
  -n, --nodes=sparse|dense   Are node IDs sparse or dense?
  -a, --attr-prefix=PREFIX   Optional prefix for attributes, defaults to '@'
```
`--location-store=dense_file_array` means store the locatoins into the local disk?
My disk are SSD,
What does `--list-location-stores` means?

**Comment by lygstate** [comment]
The command
`
./minjur/build/minjur-mp -e minjur.err.log --nodes=dense /mnt/g/work/data/planet-latest-2017-05-04.osm.pbf > /mnt/g/work/data/planet-latest-2017-05-04.osm.json
`
I didn't using `-l dense_file_array` but  Using the 'dense_mmap_array' location store
And so that using pagefile in WSL(Bash on Ubuntu on Windows )

The time consumed about 10 hours
```
Start time: 2017-05-26-11:05 PM
End time: 2017-05-27-7:55 AM
```

```
Using the 'dense_mmap_array' location store. Use -l or -n to change this.
Reading from '/mnt/g/work/data/planet-latest-2017-05-04.osm.pbf'...
Pass 1...
Pass 1 done
Pass 2...
Pass 2 done
Number of geometry errors (not written to output): 9534
Done.
```
