### ISSUE TITLE
"Support for map type 'dense_mem_array' not compiled into this binary"

### ISSUE THREAD

**Issue by MateoV** [mapbox/minjur#4]
@joto I'm getting this error since this morning when using `-n dense`. This is on a fresh EC2 install. Any insights?

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Support for map type 'dense_mem_array' not compiled into this binary.
Aborted (core dumped)
```

**Comment by joto** [comment]
My error. Just fixed it. Please try again with newest minjur and newest libosmium.
