### ISSUE TITLE
Option to only generate node locations cache (bypass geojson output)

### ISSUE THREAD

**Issue by MateoV** [mapbox/minjur#5]
@joto does it make sense to have an option that only outputs the node locations cache when the geojson is not needed, for instance when updating? Would bypassing geojson creation speed up the process?

cc @aaronlidman

**Comment by joto** [comment]
The GeoJSON is always needed, even for updates. The reason to run `minjur` is the GeoJSON. Creating the locations cache is only the side effect needed for updates.

If you only want to generate a locations cache file, there are other ways to do it. Some experimental code is at https://github.com/osmcode/experimental-osm-db .

**Comment by MateoV** [comment]
OK, thanks for the explanation.
